# Generated by Django 5.1 on 2025-01-18 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('view', models.BooleanField(default=False)),
                ('lastModifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
