# Generated by Django 5.1 on 2025-01-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmrset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='sortOrder',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
