# Generated by Django 5.1 on 2025-01-15 10:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomType', models.IntegerField()),
                ('weekPrice', models.IntegerField()),
                ('monthPrice', models.IntegerField()),
                ('weekDeposit', models.IntegerField()),
                ('monthDeposit', models.IntegerField()),
                ('lastModifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomType', models.IntegerField()),
                ('priceType', models.IntegerField()),
                ('price', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('startDate', models.DateField(default=django.utils.timezone.now)),
                ('endDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastModifiedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
