# Generated by Django 5.1 on 2025-01-15 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='endDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
