# Generated by Django 5.1 on 2025-01-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_reserve_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='userId',
        ),
    ]
